---
- hosts: lamp-www
  become: yes

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.repo-epel
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.phpmyadmin
    # - geerlingguy.php-memcached
    # - ansible-role-phpmyadmin

  tasks:
    - name: Remove the Apache test page.
      file:
        path: /var/www/html/index.html
        state: absent
    # - name: Copy our fancy server-specific home page.
    #   template:
    #     src: templates/index.php.j2
    #     dest: /var/www/html/index.php
