---
- hosts: lamp-www
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    # - name: disable fingerprint checking that may be enabled; when enabled, causes ssh issues
    #   command: authconfig --disablefingerprint --update

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.repo-epel
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    # - geerlingguy.phpmyadmin
    # - geerlingguy.php-memcached
    - ansible-role-phpmyadmin

  tasks:
    - name: Set selinux httpd_can_network_connect flag on and keep it persistent across reboots
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: Set selinux httpd_can_network_connect_db flag on and keep it persistent across reboots
      seboolean:
        name: httpd_can_network_connect_db
        state: yes
        persistent: yes
