---
#### IPTABLES ####
firewall_allowed_tcp_ports:
  - "22"
  - "80"

#### NTP ####
ntp_manage_config: true
ntp_servers:
  - ntp1.wichita.edu
  - ntp2.wichita.edu

#### APACHE ####
apache_create_vhosts: true
apache_global_vhost_settings: |
  DirectoryIndex index.php index.html

apache_vhosts:
  # Additional properties:
  # 'serveradmin, serveralias, allow_override, options, extra_parameters'.
  - servername: "cslab-db-web.cs.wichita.edu"
    serveralias: "www.cslab-db-web"
    documentroot: "/var/www/html"
    extra_parameters: |
        RedirectMatch permanent ^/$ /phpmyadmin

#### PHPMYADMIN ####
phpmyadmin_mysql_host: "{{ hostvars[groups['lamp-db'][0]]['ansible_host'] }}"
phpmyadmin_mysql_port: "3306"
# phpmyadmin_mysql_socket: "/var/lib/mysql/mysql.sock"
phpmyadmin_mysql_user: ''
phpmyadmin_mysql_password: ''

phpmyadmin_allow_access_ip:
  - 10.250.0
  - 172
  - 156.26
  - 192.168.250
  - 192.168.251

# phpmyadmin_allow_setup_ip:
  # - "{{ hostvars[groups['lamp-varnish'][0]]['ansible_host'] }}"
