---
- src: geerlingguy.firewall
- src: geerlingguy.ntp
# - src: geerlingguy.repo-epel

# switching andrewrothstein's role to benroose's forked version
# - src: andrewrothstein.docker-machine # upstream galaxy role
- src: https://github.com/benroose/ansible-role-docker-machine/ # URL to my fork of Galaxy role's GitHub repo
  version: driver-kvm # the name of my patch branch
  name: andrewrothstein.docker-machine # save role with name it had when downloaded from Galaxy
