---
# tasks for extra software installation
- name:  Install required software packages on Red Hat system
  yum:
    state: present
    name: "{{ item }}"
  with_items:
    - "{{ installation_packages }}"
  become: yes
  when: ansible_os_family == "RedHat"

- name:  Install required software packages on Debian system
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - "{{ installation_packages }}"
  become: yes
  when: ansible_os_family == "Debian"

