---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    stack:
      - name: mariadb-test
      - access: wsu_only
      - public_net: Public_971
      - key: testing

    instances:
      - name: a4d-lamp-varnish
        group: "lamp-varnish"
        # security_group: ["default", "a4d_lamp_http"]
      - name: a4d-lamp-www-1
        group: "lamp-www"
        # security_group: ["default", "a4d_lamp_http"]
      - name: a4d-lamp-www-2
        group: "lamp-www"
      #   # security_group: ["default", "a4d_lamp_http"]
      - name: a4d-lamp-db-1
        group: "lamp-db"
        # security_group: ["default", "a4d_lamp_db"]
      - name: a4d-lamp-db-2
        group: "lamp-db"
        # security_group: ["default", "a4d_lamp_db"]
      # - name: a4d-lamp-memcached
      #   group: "lamp-memcached"
        # security_group: ["default", "a4d_lamp_memcached"]

  tasks:
    - name: Provision private network, security groups, and instances.
      ignore_errors: True
      register: stack_create
      os_stack:
        name: "{{ stack.name }}"
        # tag: "{{ tag_name }}"
        state: present
        template: stack_openstack.yml
        environment:
          - env_openstack.yml
          parameters:
            stack_access: "{{ stack.access }}"
            public_net: "{{ stack.public_net }}"
            key: "{{ stack.key }}"
      register: stack_results

  # may want to "add_hosts" in a future update.

  - name: Refresh dynamic inventory with new hosts after stack creation.
    meta: refresh_inventory
    when: stack_results is defined

 
# Run some general configuration on all openstack hosts.
- hosts: lamp
  gather_facts: false

  tasks:
    # - name: Wait for port 22 to become available.
    #   local_action: "wait_for port=22 host={{ inventory_hostname }}"

    - name: Set selinux into 'permissive' mode.
      selinux: policy=targeted state=permissive
      become: yes
